language: elixir

sudo: required

services:
  - docker

notifications:
  email: false

elixir:
  - 1.4.5
  - 1.5.2
  - 1.6.4

otp_release:
  - 20.3
  - 19.2

script:
  - mix local.rebar --force
  - mix local.hex --force
  - make dist
  - echo 127.0.0.1 kafka1 | sudo tee -a /etc/hosts
  - echo 127.0.0.1 kafka2 | sudo tee -a /etc/hosts
  - echo 127.0.0.1 kafka3 | sudo tee -a /etc/hosts
  - make docker-start
  - make integ
