language: elixir

sudo: required

services:
  - docker

notifications:
  email: false

elixir:
  - 1.4.5
  - 1.5.2

otp_release:
  - 20.1
  - 19.2

script:
  - mix local.rebar --force
  - mix local.hex --force
  - make dist
  - echo 127.0.0.1 kafka1 kafka2 kafka3 | sudo tee -a /etc/hosts
  - make docker-start
  - make integ
