language: elixir

sudo: required

services:
  - docker

before_install:
  - curl -L https://github.com/docker/compose/releases/download/1.6.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin/

notifications:
  email: false

elixir:
  - 1.4.5
  - 1.5.2

otp_release:
  - 20.1
  - 19.2

script:
  - mix local.rebar --force
  - mix local.hex --force
  - make dist
  - make docker-compose.yml
  - sudo make docker-start
  - make integ
