language: elixir

sudo: required

services:
  - docker

before_install:
  - curl -L https://github.com/docker/compose/releases/download/1.6.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin/

notifications:
  email: false

elixir:
  - 1.2.2
  - 1.2.3
  - 1.3.0
  - 1.3.1
  - 1.3.2
  - 1.3.3

otp_release:
  - 19.1
  - 19.0
  - 18.3
  - 18.1
  - 18.0

script:
  - mix local.rebar --force
  - mix local.hex --force
  - make dist
  - sudo make docker-start
  - make integ
  - sudo make docker-stop
