# File: Kafe.Records.ex
# This file was generated by rebar3_elixir (https://github.com/botsunit/rebar3_elixir)
# MODIFY IT AT YOUR OWN RISK AND ONLY IF YOU KNOW WHAT YOU ARE DOING!
defmodule Kafe.Records do
  require Record
  import Record, only: [defrecord: 2, extract: 2]

  defrecord :message, extract(:message, from_lib: "kafe/include/kafe_consumer.hrl")
end
