-define(DEFAULT_IP, enet:get_loopback()).
-define(DEFAULT_PORT, 9092).
-define(DEFAULT_CLIENT_ID, <<"kafe">>).
-define(DEFAULT_CORRELATION_ID, 0).
-define(DEFAULT_API_VERSION, 0).

-define(PRODUCE_REQUEST, 0).
-define(FETCH_REQUEST, 1).
-define(OFFSET_REQUEST, 2).
-define(METADATA_REQUEST, 3).

-define(DEFAULT_OFFSET_PARTITION, 0).
-define(DEFAULT_OFFSET_TIME, -1).
-define(DEFAULT_OFFSET_MAX_SIZE, 65535).

-define(BITMASK_REQUIRE_ACK, 1).
-define(DEFAULT_PRODUCE_REQUIRED_ACKS, 0).
-define(DEFAULT_PRODUCE_SYNC_TIMEOUT, 5000).
-define(DEFAULT_PRODUCE_PARTITION, 0).
